# Generated by Django 3.0.8 on 2020-09-30 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.BillingAddress'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='internal_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
